version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: aws/deployment/application_stop/stop_cloudplanning.sh
      timeout: 20
      runas: ec2-user
ApplicationStart:
    - location: aws/deployment/application_start/start_cloudplanning.sh
      timeout: 20
      runas: ec2-user
